### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by yebai** [TuringLang/DistributionsAD.jl#1]
Does it make sense to rename this package to a slightly more generic name (e.g. `DistributionsX`) to accommodate other Distributions extension, e.g. potential GPU support?

Related: https://discourse.julialang.org/t/anything-like-distributions-jl-for-gpu/17147/15

**Comment by yebai** [comment]
cc @xukai92 @trappmartin @mohamed82008

**Comment by trappmartin** [comment]
Sounds good. Maybe we should choose a more telling name than `DistributionsX` like `DistributionsExtensions`?

**Comment by mohamed82008** [comment]
I think GPU support should be left out for now. Supporting AD for all distributions is a sufficiently difficult task. Besides this package may be dissolved into other AD packages at some point by other devs, so it is good to keep its scope minimal. Not depending on CUDA packages is also important since not all computers use CUDA and other packages like Gen or Soss which require AD on distributions may not want to install CUDA to use this package. I think we can make `CuDistributions` later.

**Comment by xukai92** [comment]
I feel there are a lot of overlapping between making distributions AD comptaible and GPU/CUDA comptaible. What would be a seperate package CuDistributions.jl looks like?
