### ISSUE TITLE
`BetaPrime` distribution has broken tests with the recent release of Distributions. 

### ISSUE THREAD

**Issue by yebai** [TuringLang/DistributionsAD.jl#196]
See https://github.com/TuringLang/DistributionsAD.jl/pull/185#issuecomment-901466657

**Comment by devmotion** [comment]
It seems the choice of parameter alpha was just unfortunate since `alpha = 1` leads to the special case where `xlogy` ends up in the always-zero branch. Setting the parameter to 1.5, as done in the recent PRs, fixes the issue. Unfortunately, the PRs revealed many Zygote issues (somehow we end up with NamedTuple instead Tangent in some intermediate step and therefore Zygote throws an error) so the PRs can't be released currently.

**Comment by devmotion** [comment]
More details: https://github.com/TuringLang/DistributionsAD.jl/pull/198#discussion_r699237854
