### ISSUE TITLE
ERROR: Package DistributionsAD errored during testing

### ISSUE THREAD

**Issue by iajzenszmi** [TuringLang/DistributionsAD.jl#224]
ERROR: LoadError: LoadError: Some tests did not pass: 85 passed, 0 failed, 3 errored, 0 broken.
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/others.jl:1
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/runtests.jl:52
ERROR: Package DistributionsAD errored during testing
ERROR: LoadError: LoadError: Some tests did not pass: 85 passed, 0 failed, 3 errored, 0 broken.
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/others.jl:1
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/runtests.jl:52
ERROR: Package DistributionsAD errored during testing
ERROR: LoadError: LoadError: Some tests did not pass: 85 passed, 0 failed, 3 errored, 0 broken.
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/others.jl:1
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/runtests.jl:52
ERROR: Package DistributionsAD errored during testing
ERROR: LoadError: LoadError: Some tests did not pass: 85 passed, 0 failed, 3 errored, 0 broken.
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/others.jl:1
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/runtests.jl:52
ERROR: Package DistributionsAD errored during testing
ERROR: LoadError: LoadError: Some tests did not pass: 85 passed, 0 failed, 3 errored, 0 broken.
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/others.jl:1
in expression starting at /home/ian/.julia/packages/DistributionsAD/dKKOw/test/runtests.jl:52
ERROR: Package DistributionsAD errored during testing

**Comment by devmotion** [comment]
Which version did you test? I just ran the tests for the latest release locally, and they passed.

**Comment by iajzenszmi** [comment]
I ran it on Julia version 1.0.7.  by sudo snap install julia. The up to
date current version is Julia version 1.7.2. The make for this version is
still running on my system and when it is installed I will run
julia DistributionsAD.jl again.
Ian Martin Ajzenszmidt

**Comment by devmotion** [comment]
Recent versions of DistributionsAD only support Julia >= 1.3, so it seems you tested an old version of this package.

Nowadays it's probably best to use at least Julia 1.6 since it is the new LTS and hence many packages have dropped support for Julia < 1.6. Usually the best way to install Julia is to use the official binaries (I've seen issues with incompatible system libraries with Julia packages served by some Linux distributions such as ArchLinux, so it's best to avoid these packages IMO). To simplify the process of installing and switching between different Julia versions you can use `juliaup` (which is supposed to become the official installation procedure at some point): https://github.com/JuliaLang/juliaup

**Comment by devmotion** [comment]
I'll close this issue. Please feel free to reopen if the issue re-occurs with the latest release of DistributionsAD.
