### ISSUE TITLE
GPU friendly distributions

### ISSUE THREAD

**Issue by nmheim** [TuringLang/DistributionsAD.jl#98]
```julia
using CUDA
using DistributionsAD
d = DistributionsAD.TuringMvNormal(cu(rand(2)), cu(rand(2)))
rand(d)
```
The above gives me an isbits error, because `randn` here: https://github.com/TuringLang/DistributionsAD.jl/blob/809bdc7ba7ee46363cfa8b226e9d5b2598469056/src/multivariate.jl#L127 returns an `Array`. Is there a nicer way of dealing with this than something like
```julia
d.m .+ d.σ .* randn!(similar(d.m, length(d), n...))
```
?

**Comment by mohamed82008** [comment]
I think we can overload `rand` for `TuringMvNormal` and `CuArrays` to call `curand` or the CUDA version of `rand`.

**Comment by xukai92** [comment]
`rand!` and `randn!` are also defined for `CuArray` [here](https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/curand/random.jl) but only with `rng::CUDA.CURAND.RNG` (defined [here](https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/curand/random.jl#L16)) which can be created using `rng = CUDA.CURAND.generator()` (defined [here](https://github.com/JuliaGPU/CUDA.jl/blob/master/lib/curand/CURAND.jl#L25)).

I meet the exact same problem before when I was coding my own mini distribution [collection](https://github.com/xukai92/MLToolkit.jl/blob/master/src/DistributionsX/DistributionsX.jl) and ended up introducing functions like below.
```julia
rand!(::AbstractRNG, x::CuArray, dims::Int...) = rand!(CUDA.CURAND.generator(), x, dims...)
randn!(::AbstractRNG, x::CuArray, dims::Int...) = randn!(CUDA.CURAND.generator(), x, dims...)
```
so that `rand!` and `randn!` would work for normal `rng` (otherwise they will be forward to scalar operations I believe). But as you can expect, the randomness is not controlled any more by the passed-in `rng.

In fact, although `randn!(similar(..))` is faster than `cu(randn(...))`, it's really not the bottleneck of computation in any deep learning setting. Therefore, another choice is to introduce something like`randsimilar` and `randnsimilar`, can do below
```julia
randsimilar(rng, x, dims...) = rand(rng, dims...)
randsimilar(rng, x::CuArray, dims...) = cu(rand(rng, dims...))
```
and use `randsimilar` across the codebase.
This approach will control the whole randomness via the passed-in, CPU `rng`.

As a side note for this to work with Zygote.jl, you will need to do `Zygote.@nograd randsimilar` (like what I did [here](https://github.com/xukai92/MLToolkit.jl/blob/master/src/DistributionsX/ad.jl#L5-L6)).

**Comment by nmheim** [comment]
Hmm, but then we would have to depend on `CuArrays` right? Why do we need to control randomness via the CPU `rng`?

**Comment by xukai92** [comment]
> Hmm, but then we would have to depend on CuArrays right?

I'm not sure. I remember there are workaround to not dedpend on CUDA.jl. Maybe look at how Flux deal with it.

> Why do we need to control randomness via the CPU rng?

I don't mind it's a CPU or GPU RNG, but we should only need to specify only one RNG.
Ideally, we want to something like

```julia
rng = ...
sample(rng, ...) # or optimize(rng, ...)
```
of which the randomness is completely controlled by `rng` right? Not that the same issue exists for `seed!` as well  - you would need to do two `seed!`, for both CPU and PUG RNG so that the computation is reproducible.

The issue here is that we don't know if some of the computation involved is using CPU or GPU really. For example, even if we ended up generating most of the random number on GPUs, stuff like `if rand(rng) < 0.5 ... else ... end` might still needed.

I don't know what's the best way to achieve so. The proposal I made is just one option.

**Comment by nmheim** [comment]
Ahh, yes of course, I get the point of having one `rng` control all of the randomness.
I am not sure if there is a way around depending on `CUDA.jl`, at least not according to their docs:

https://juliagpu.gitlab.io/CUDA.jl/installation/conditional/

Flux is using the last one of the options listed there.
